[DF-7] All Photos Page
yee2542/FluentSearch-FE pull request #34
Opened 2021-01-10 19:33 UTC by octobrekids

This branch including by
- All photos page
- All photos page test
- All photos page storybook 
- All photos page layout

2021-01-11 07:22 UTC, yee2542 commented
I'd prefer `photo` the `allphotho` for this module name

2021-01-11 07:23 UTC, yee2542 commented
I'd prefer `photo` the `allphotho` for this module name

2021-01-14 22:50 UTC, yee2542 requested changes

2021-01-15 14:47 UTC, octobrekids commented on src/common/components/Loader/index.tsx
> +      <div className="lds-ellipsis">
fix here d8d6e6c9deb64c5e68c963fb2b134a54b4cf419a

2021-02-05 15:30 UTC, yee2542 commented
WTF
- select not implment
- photoRuducer not implment
- too big on `/pages/allphotos/index.tsx`
- too fragment on `LightBox` component
- no test
- `#lightbox-img` should be a styledcomponent code base

2021-02-05 15:44 UTC, yee2542 commented
WTF
- select not implment
- photoRuducer not implment
- too big on `/pages/allphotos/index.tsx`
- too fragment on `LightBox` component
- no test
- `#lightbox-img` should be a styledcomponent code base
- too many unused components e.g. LoadedImage, GroupThumbnailPhoto
- pages `/upload` missing layout

2021-02-05 15:45 UTC, yee2542 commented
> WTF
> 
> * select not implment
> * photoRuducer not implment
> * too big on `/pages/allphotos/index.tsx`
> * too fragment on `LightBox` component
> * no test
> * `#lightbox-img` should be a styledcomponent code base
> * too many unused components e.g. LoadedImage, GroupThumbnailPhoto
> * pages `/upload` missing layout

2021-02-05 15:46 UTC, merged